2025-03-24 11:44:43,124 INFO    MainThread:4172057 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2025-03-24 11:44:43,124 INFO    MainThread:4172057 [wandb_setup.py:_flush():76] Configure stats pid to 4172057
2025-03-24 11:44:43,124 INFO    MainThread:4172057 [wandb_setup.py:_flush():76] Loading settings from /common/home/hg343/.config/wandb/settings
2025-03-24 11:44:43,124 INFO    MainThread:4172057 [wandb_setup.py:_flush():76] Loading settings from /common/home/hg343/Research/accelerate_combo_option/src/wandb/settings
2025-03-24 11:44:43,124 INFO    MainThread:4172057 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2025-03-24 11:44:43,124 INFO    MainThread:4172057 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'src/combo_stock_frontier_data_preprocessor_forked.py', 'program_abspath': '/common/home/hg343/Research/accelerate_combo_option/src/combo_stock_frontier_data_preprocessor_forked.py', 'program': '/common/home/hg343/Research/accelerate_combo_option/src/combo_stock_frontier_data_preprocessor_forked.py'}
2025-03-24 11:44:43,124 INFO    MainThread:4172057 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-03-24 11:44:43,124 INFO    MainThread:4172057 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-03-24 11:44:43,124 INFO    MainThread:4172057 [wandb_init.py:_log_setup():520] Logging user logs to /common/home/hg343/Research/accelerate_combo_option/src/wandb/run-20250324_114443-cun7geg1/logs/debug.log
2025-03-24 11:44:43,124 INFO    MainThread:4172057 [wandb_init.py:_log_setup():521] Logging internal logs to /common/home/hg343/Research/accelerate_combo_option/src/wandb/run-20250324_114443-cun7geg1/logs/debug-internal.log
2025-03-24 11:44:43,124 INFO    MainThread:4172057 [wandb_init.py:init():560] calling init triggers
2025-03-24 11:44:43,124 INFO    MainThread:4172057 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2025-03-24 11:44:43,124 INFO    MainThread:4172057 [wandb_init.py:init():610] starting backend
2025-03-24 11:44:43,124 INFO    MainThread:4172057 [wandb_init.py:init():614] setting up manager
2025-03-24 11:44:43,125 INFO    MainThread:4172057 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-24 11:44:43,128 INFO    MainThread:4172057 [wandb_init.py:init():622] backend started and connected
2025-03-24 11:44:43,131 INFO    MainThread:4172057 [wandb_init.py:init():711] updated telemetry
2025-03-24 11:44:43,151 INFO    MainThread:4172057 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2025-03-24 11:44:43,360 INFO    MainThread:4172057 [wandb_run.py:_on_init():2396] communicating current version
2025-03-24 11:44:43,390 INFO    MainThread:4172057 [wandb_run.py:_on_init():2405] got version response upgrade_message: "wandb version 0.19.8 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-03-24 11:44:43,391 INFO    MainThread:4172057 [wandb_init.py:init():795] starting run threads in backend
2025-03-24 11:44:56,555 INFO    MainThread:4172057 [wandb_run.py:_console_start():2374] atexit reg
2025-03-24 11:44:56,556 INFO    MainThread:4172057 [wandb_run.py:_redirect():2229] redirect: wrap_raw
2025-03-24 11:44:56,556 INFO    MainThread:4172057 [wandb_run.py:_redirect():2294] Wrapping output streams.
2025-03-24 11:44:56,556 INFO    MainThread:4172057 [wandb_run.py:_redirect():2319] Redirects installed.
2025-03-24 11:44:56,557 INFO    MainThread:4172057 [wandb_init.py:init():838] run started, returning control to user process
2025-03-24 11:45:36,413 INFO    MainThread:4172057 [wandb_run.py:_finish():2103] finishing run jglppk/expediating_comb_financial_market_matching/cun7geg1
2025-03-24 11:45:36,413 INFO    MainThread:4172057 [wandb_run.py:_atexit_cleanup():2343] got exitcode: 1
2025-03-24 11:45:36,414 INFO    MainThread:4172057 [wandb_run.py:_restore():2326] restore
2025-03-24 11:45:36,414 INFO    MainThread:4172057 [wandb_run.py:_restore():2332] restore done
